export enum IpcChannelEnum {
  SERVICE_PROJECT_START_LOAD_FILES = 'SERVICE_PROJECT_START_LOAD_FILES',
  SERVICE_PROJECT_GET_FILES = 'SERVICE_PROJECT_GET_FILES',
  SERVICE_PROJECT_COPY_FILES = 'SERVICE_PROJECT_COPY_FILES',
  SERVICE_PROJECT_START_READ_FILES = 'SERVICE_PROJECT_START_READ_FILES',
  SERVICE_PROJECT_READ_FILES = 'SERVICE_PROJECT_READ_FILES'
}
